name: Auto Label Issues

on:
  issues:
    types: [opened, edited]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-label issues based on title
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.issue.title.toLowerCase();
            const labels = [];

            if (title.includes('bug')) {
              labels.push('bug');
            }
            if (title.includes('feature') || title.includes('enhancement')) {
              labels.push('enhancement');
            }
            if (title.includes('question')) {
              labels.push('question');
            }

            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: labels
              });
            }
